### ISSUE TITLE
Support for hourly interval data points

### ISSUE THREAD

**Issue by appletalk** [emcniece/bchydro#1]
This is a great for providing access to BC Hydro's data, since they do not have an API you can access directly.  

The addition of the hourly interval data would be handy for some use cases.

**Comment by emcniece** [comment]
I agree, hourly data would be a fantastic feature. I just tested the `consumption-data.html` chart endpoint - it doesn't expose this in the website, but there is a header for `Granularity=daily` and changing it to `Granularity=hourly` actually works!

```xml
<Point type="SMI" quality="ACTUAL" dateTime="2020-08-07T00:00:01-07:00" endTime="2020-08-07T01:00:00-07:00" value=".78" cost="0.08"/>
<Point type="SMI" quality="ACTUAL" dateTime="2020-08-07T01:00:01-07:00" endTime="2020-08-07T02:00:00-07:00" value=".48" cost="0.05"/>
<Point type="SMI" quality="ACTUAL" dateTime="2020-08-07T02:00:01-07:00" endTime="2020-08-07T03:00:00-07:00" value=".47" cost="0.05"/>
<Point type="SMI" quality="ACTUAL" dateTime="2020-08-07T03:00:01-07:00" endTime="2020-08-07T04:00:00-07:00" value=".48" cost="0.05"/>
```

**Comment by planetawylie** [comment]
I've been trying to rewrite the code to login to FortisBC but I'm not able to get past the login page. It looks to be doing things a bit differently in that department so might not be possible.

**Comment by emcniece** [comment]
@planetawylie - FortisBC integration is an interesting idea. I don't have an account with them, and given the name of this package it might be out of scope for this repo. Nevertheless I'll keep that in mind, maybe we could start a new repo and analyze the other site.

@appletalk - @Nebual has just solved a handful of problems for us, and he added support for hourly granularity in https://github.com/emcniece/bchydro/pull/2 ! I'll release v0.7 shortly. Unfortunately it seems that while we can obtain hourly granularity, it only comes in bulk and refreshes every 24h... so we can't get the real-time-ish value of the last hour of electricity usage.

To see hourly granularity you can now do the following:

```py
async def main():
    a = BCHydroApi(os.environ.get("BCH_USER"), os.environ.get("BCH_PASS"))
    await a.authenticate()
    usage = await a.get_usage(hourly=True)
```

I'll mark this as closed as the closest possible solution to the feature request has been met. It does make me sad that we can't get closer to real-time data, but I plan to chase down the BCHydro dev team to see if there are any other options.

**Comment by benpye** [comment]
@emcniece I've been playing around with this, did you ever get any traction about closer to realtime data? I was playing with the `export-consumption.html` endpoint as well but it seems the same.

**Comment by emcniece** [comment]
Unfortunately not. The data returned from the API is only for the previous day, regardless of the granularity. It appears we can't get anything close to real-time.
